### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by smartnavdeep** [smartnavdeep/Pig-Latin#13]
Hi Ved there is another problem, Here is the gif..

![Pig Latin](https://user-images.githubusercontent.com/65970997/100857499-be82d380-34b2-11eb-9a44-e8e936b4b955.gif)

Hope you will fix that.

Regards,
Navdeep.

**Comment by Ved-programmer** [comment]
Yes, I will fix it.

**Comment by Ved-programmer** [comment]
I have fixed it, I know that you are not free after 8:30 so I am leaving this message. You are probably reading this message tomorrow. Download and run the code now and see if it fixes the issue

**Comment by smartnavdeep** [comment]
Wo it fixed

**Comment by Ved-programmer** [comment]
well, I see that you have also merged the two files, great job. I will
start work on a button which when clicked gets us to the website.
