### ISSUE TITLE
javascript and python don't match

### ISSUE THREAD

**Issue by Ved-programmer** [smartnavdeep/Pig-Latin#15]
The javascript code that you have written don't match the python code I have written. There are some exceptions like honest, it gets converted to honestyay not onesthay as the first sound is a vowel sound so the rule for vowel should be followed. So you should have a look at my python code and update your javascript code.

**Comment by smartnavdeep** [comment]
Ok I will try but right no I'm having class, i will do it in the evening

**Comment by Ved-programmer** [comment]
ok no problem.

**Comment by smartnavdeep** [comment]
Hi Ved, 

I tried reading all the rules of pig Latin an also saw in other online Pig Latin translators that the word honest or other similar words won't be counted as exceptions, it only sees the vowels not the pronunciation, so the Python code need to be altered, so if you say ok I will alter the python code

**Comment by Ved-programmer** [comment]
read this article: https://en.wikipedia.org/wiki/Pig_Latin

**Comment by Ved-programmer** [comment]
the article clearly states that for words that begin with vowel sounds, the vowel is left alone, and most commonly 'yay' is added to the end. so honest becomes honestyay

**Comment by smartnavdeep** [comment]
yeah but we shouldn't be making more difficult, um anyways, ok I will, but actually other translator of pig-Latin don't follow this but no problem, we will follow, the thing is that I will be having exams from next week I can't but I will make the needed changes

**Comment by smartnavdeep** [comment]
till then lets not close this issue

**Comment by Ved-programmer** [comment]
ok fine, make the changes. Once done you can close the issue.

**Comment by smartnavdeep** [comment]
Ok do I have added the features you asked and I will be closing this issue, if there are more problems with the altered code, then you can report it , I will respond.
