### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by code-edict** [smartnavdeep/Pig-Latin#21]
Hi Navdeep, as you asked I'm creating a test issue for you since the bot isn't getting triggered by you.

**Comment by smartnavdeep** [comment]
Okay so the bot is working perfectly

**Comment by smartnavdeep** [comment]
thank you @code-edict, since I was the owner for this repo, maybe the bot wasn't getting triggered when I open the issue.

**Comment by code-edict** [comment]
your welcome : )
