### ISSUE TITLE
Some Issues

### ISSUE THREAD

**Issue by smartnavdeep** [smartnavdeep/Pig-Latin#9]
# Hi

When I downloaded the code and checked the gui, it is actually very and extended over the screen,

Screenshots :

![Screenshot (84)](https://user-images.githubusercontent.com/65970997/100747262-d2bdc680-3407-11eb-8710-006c4f96f9a3.png)
![Screenshot (85)](https://user-images.githubusercontent.com/65970997/100747265-d3eef380-3407-11eb-9939-734129e5c4d7.png)
![Screenshot (86)](https://user-images.githubusercontent.com/65970997/100747267-d4878a00-3407-11eb-8446-e081e1d7ff2e.png)
![Screenshot (83)](https://user-images.githubusercontent.com/65970997/100747268-d4878a00-3407-11eb-8141-07454b6e8ecd.png)

another issue, well it is that too many files are not that good for it, so I hope that you will be able to manage the task of keeping the files in one file, I know that pycache get formed when a file import a file, but when some one else sees it, they may complain about it that what is this pycache,
so I hope that you will be able to merge all that files into one, but if it's not possible, then no problem, and yeah please make a button which when clicked, is going to take the user to our original repository, and I will tell you how,

```python
# There is a module known as webbroser, which open urls in the default browser, it comes inbuilt with python
import webbrowser
webbrowser.open("www.youtube.com")
```

Overall the GUI is great !

Regards,
Navdeep

**Comment by Ved-programmer** [comment]
For the allignment issue, the problem is that I have done pixel by pixel positioning, and the pixel by pixel positioning is different on different screens. So it is looking perfect on my laptop but is different on yours. I will change it from pixel by pixel to relational, I will look into the stuff like putting all in one file, button when clicked takes us to the original repository etc lates, because the alignment is the main issue. and the most difficult one too.

**Comment by smartnavdeep** [comment]
Oh, see, btw I can give an idea of it cause I'm familiar with web development, maybe (i don't know if it works) there will be something like grid system, or instead of the pixel by pixel method, is there any percentage my percentage method

**Comment by Ved-programmer** [comment]
ya, actually there is a grid system. I had used pixel by pixel method to get it done fast. I will use the grid system. It will take a little bit of time(converting everything into a grid) but it can be done. I will need about two days. I suggest you learn about tkinter, it comes built in with python

**Comment by smartnavdeep** [comment]
Yeah actually I learn't tkinter, 3 month back but then I started learning web development, thus I lost the practise of it.

**Comment by Ved-programmer** [comment]
oh, ok

**Comment by smartnavdeep** [comment]
Btw the javaskript part of the website is almost done, but it will take some more time cause there are some things which python can and javaskript can't do
